### PR TITLE
Add optional support for cljs with reagent

### PR DESCRIPTION
**Pull request by lsnape**
Clojurescript support by supplying an optional `--reagent-webapp` argument. You can test the snapshot by running:

`lein new mr-clojure testapp --snapshot -- reagent-webapp`

It's heavily based on the Reagent Clojurescript template. I've trimmed it down and made it fit our standard layout as much as possible. It's been deployed internally a couple of times and is working as expected.

One compromise I've made is splitting the deps into 2 to make the conditional rendering of the project.clj easier. We could build the deps as strings and sort them in the code that renders that template, but that's a bit more work.

With the exception of upping the Clojure version to 1.7, the project with no args is unchanged.

### CODE REVIEW

**Comment by dmcgillen** [comment]
Looks great. A couple of minor points:

1. Would be nice to add the following to the .gitignore file so things like minified css and output javascript don't get put into repos. I think .DS_Store should be in the .gitignore file generally (not just applicable to cljs):

.DS_Store
{{#cljs-app?}}
/resources/public/js
figwheel_server.log
*.min.css
{{/cljs-app?}}

2. I can't view the favicon - what is it? If we do want to put a favicon with the skeleton, in our latest project we've put it under an images subdirectory and referred to it by location in the code rather than relying on browsers picking up the favicon from a known location (which didn't work once we started going through our proxy service)

**Comment by lsnape** [comment]
I've updated the .gitignore files and moved the favicon into a new `img` subdirectory. Also added a link element in the head to the favicon. The favicon is a pink Ike that I took from the corporate site :)

**Comment by dmcgillen** [comment]
Ah, cool :) I can't see the added link, is it in page_frame?

I'm also wondering about the "Clojurescript has not been compiled" message that appears in page_frame, because it always flashes up (even in production) before the actual page is seen. If the page is slow to load it can be up for quite a few seconds and isn't really true (as the code has been compiled). Might be a bit confusing to non devs using a UI. Maybe we can restrict it to when in dev-mode only? What do you think?

**Comment by lsnape** [comment]
Oops thought I added the link to favicon in page_frame.clj. That's done now.

Loading message is something that Ian and I took out yesterday when we were deploying. Have changed to a more generic 'Loading..' message.

**Comment by joelittlejohn** [comment]
Might also be worth [modifying the Travis CI build command](http://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step) to include this template too.

**Comment by dmcgillen** [comment]
Sorry, one other thing - is this stuff ready to go into the readme or are you waiting until a further iteration where testing etc is introduced?

**Comment by lsnape** [comment]
@dmcgillen Not updated the readme yet. I think it should be included in this merge rather than in the future, so will have a look at doing that.

@joelittlejohn have updated the `.travis.yaml`. Didn't see it rerun though. Is there a way to force retrigger it?

**Comment by joelittlejohn** [comment]
@lsnape Travis doesn't seem to want to notice your latest force push. You can rerun builds [here](https://github.com/mixradio/mr-clojure) but I only seem to be able to force a rerun that builds the old commit hash.

**Comment by lsnape** [comment]
The travis build didn't start because the `.travis.yaml` was malformed. This is fixed and working now.

I've added a few lines to the readme on how to generate and start the clojurescript project. The current size of the readme feels about right. I'm concerned that adding any detailed usage guidelines on the Clojurescript variant project could make it too long and bloated. Creating a getting started blog post and linking to it might be a better idea?

**Comment by dmcgillen** [comment]
Sounds good to me. I'm not sure about how a blog post would fare as it becomes out of date with changes to the template, but maybe not much more information is really needed anyway? It would basically just be explaining how reagent works which maybe isn't necessary as people can find this elsewhere.

Everything so far looks good to me for merging / releasing anyway.

**Comment by lsnape** [comment]
Bump! Shall we get this in then?

**Comment by joelittlejohn** [comment]
Sure, sounds good. @lsnape or @dmcgillen feel free to merge and release.

**Comment by whostolebenfrog** [comment]
Make it so

**Pull request merged**
